In [1]:
import numpy as np
np.__version__

'2.5.1'

In [2]:
# create a numpy array with 1 to 100 nactural numbers 
nactural_numbers = np.arange(1,101)
nactural_numbers

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [3]:
print("The data type of the nactral_numbers :",nactural_numbers.dtype)

The data type of the nactral_numbers : int64


In [4]:
# make the array into a 2D array .
print("The current shape of the array is :",nactural_numbers.shape)
print("The dimanction of the array is  :",nactural_numbers.ndim)
nactural_numbers = nactural_numbers.reshape(4,25)
print(nactural_numbers)
print("The current shape of the array is :",nactural_numbers.shape)

The current shape of the array is : (100,)
The dimanction of the array is  : 1
[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
   19  20  21  22  23  24  25]
 [ 26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43
   44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
   69  70  71  72  73  74  75]
 [ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93
   94  95  96  97  98  99 100]]
The current shape of the array is : (4, 25)


In [5]:
# print the first row of the array / matrix we nmake.
print("The first row of the matrix is :")
print(nactural_numbers[0])

The first row of the matrix is :
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [6]:
# create a matrix with the value of zeros only .
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
# create a matrix with the value of onse only .
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [8]:
# create a matrix with a number what we want to create 
np.full((5,6),3)
# create a matrix full of the number 3 only.

array([[3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])

In [9]:
# take a user input for creating a matrix , the shape, the number want to create .
row = int (input("Enter the number of rows :"))
columns = int (input("Enter the number of columns :"))
number = int(input("Enter the number that you whould like to fill with :"))
user_matrix = np.full((row,columns),number)
print(user_matrix)

Enter the number of rows : 4
Enter the number of columns : 6
Enter the number that you whould like to fill with : 76


[[76 76 76 76 76 76]
 [76 76 76 76 76 76]
 [76 76 76 76 76 76]
 [76 76 76 76 76 76]]


In [10]:
# change the user input array with a value in the (2,3) index number . change with 45
user_matrix[2,3] = 45
print("The changed matrix is :")
print(user_matrix)

The changed matrix is :
[[76 76 76 76 76 76]
 [76 76 76 76 76 76]
 [76 76 76 45 76 76]
 [76 76 76 76 76 76]]


In [11]:
# create a randon matrix and slice the matrix with 3 rows and 2 columns .
import random
random_matrix = np.random.randint(10,100,size = (5,7))

In [12]:
print(random_matrix)

[[54 32 87 30 74 96 99]
 [80 54 55 63 52 37 71]
 [46 89 95 16 11 86 67]
 [65 28 35 17 51 14 90]
 [40 44 98 70 72 83 99]]


In [13]:
# slice the random matrix 
random_matrix[:3,:2]

array([[54, 32],
       [80, 54],
       [46, 89]], dtype=int32)

In [14]:
# slice the random matrix to the end 3 columns and 4 rows
random_matrix[1:,4:]

array([[52, 37, 71],
       [11, 86, 67],
       [51, 14, 90],
       [72, 83, 99]], dtype=int32)

In [15]:
# sapose you dont know about the size and the shape of the matrix then how you slice the last 3 x 2 muser_matrix
row_sixe = len(random_matrix)
colum_size = len(random_matrix[0])
random_matrix[row_sixe-3:,colum_size-2:]

array([[86, 67],
       [14, 90],
       [83, 99]], dtype=int32)

In [16]:
# slice the matrix from the mid 
random_matrix[1:4,2:5] # hear 4 and 5 at the last becaus 4-1 = it will run up to 3 and skip the 4 turn

array([[55, 63, 52],
       [95, 16, 11],
       [35, 17, 51]], dtype=int32)

In [17]:
array1 = np.random.randint(1,40,size=7)
array2 = np.random.randint(1,40,size=7)
print(array1)
print(array2)

[36 27 24 30 38 20  8]
[26 14 20 21 37  5 35]


In [18]:
array1.shape

(7,)

In [19]:
array2.shape

(7,)

In [20]:
# add two array. concatinate two arrays .
array3 = np.concatenate([array1,array2])
print(array3)

[36 27 24 30 38 20  8 26 14 20 21 37  5 35]


In [21]:
array3.shape

(14,)

In [22]:
# add two arrays in the verticaly
verti_add = np.vstack([array1,array2])
print(verti_add)

[[36 27 24 30 38 20  8]
 [26 14 20 21 37  5 35]]


In [23]:
# add two arrays in the horayzontal away
hory_add = np.hstack([array1,array2])
print(hory_add)

[36 27 24 30 38 20  8 26 14 20 21 37  5 35]


In [24]:
# take out the 2 nd colume from the random_matrix.
random_matrix[:,1:2] # we take the colume using the slicing 

array([[32],
       [54],
       [89],
       [28],
       [44]], dtype=int32)

In [27]:
# np.vstack([verti_add,hory_add]) ||this will not work becaus the size are differant 

In [28]:
np.vstack([verti_add,array1]) 

array([[36, 27, 24, 30, 38, 20,  8],
       [26, 14, 20, 21, 37,  5, 35],
       [36, 27, 24, 30, 38, 20,  8]], dtype=int32)