In [2]:
print("Hello World ")

Hello World 


In [3]:
import numpy as np

In [4]:
line = np.arange(25)

In [5]:
line

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [6]:
lspace=np.linspace(1,5,6)

In [7]:
lspace

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [8]:
lspace.shape

(6,)

In [9]:
arr = np.arange(99) 

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [11]:
arr = arr.reshape(3,33)

In [12]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [13]:
arr = arr.ravel()

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# Numpy Axes

In [15]:
x = [[1,2,3,4],[5,6,7,8],[7,1,2,10]]

In [16]:
arr = np.array(x)

In [17]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 7,  1,  2, 10]])

In [18]:
arr.sum(axis=0)

array([13,  9, 12, 22])

In [19]:
arr.sum(axis=1)

array([10, 26, 20])

In [20]:
arr.shape

(3, 4)

***transpose the array using the 'T'***

In [21]:
arr.T

array([[ 1,  5,  7],
       [ 2,  6,  1],
       [ 3,  7,  2],
       [ 4,  8, 10]])

In [22]:
arr.nbytes

96

In [23]:
one = ([1,65,7,90,4,2])

In [24]:
onedim = np.array(one)

In [25]:
onedim

array([ 1, 65,  7, 90,  4,  2])

In [26]:
onedim.argmax()

np.int64(3)

In [27]:
onedim.argmin()

np.int64(0)

In [28]:
onedim.argsort()

array([0, 5, 4, 2, 1, 3])

In [29]:
arr.argmax()

np.int64(11)

In [30]:
arr.argmin()

np.int64(0)

In [31]:
arr.shape

(3, 4)

In [32]:
arr.argmax(axis=0)

array([2, 1, 1, 2])

In [33]:
arr.argmin(axis=1)

array([0, 0, 1])