In [1]:
import numpy as np

**Valid Sudoku**

In [2]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [3]:
row_sum = np.sum(s,axis=1)
row_sum

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [4]:
colom_sum = np.sum(s,axis=0)
colom_sum

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [5]:
i = 0
for elem in row_sum:
    if elem != 45:
        i=1
if i == 1:
    print("The Suduko is not valid !")
else:
    print("The Suduko is valid in row wise !")

The Suduko is valid in row wise !


In [6]:
j = 0
for elem in row_sum:
    if elem != 45:
        j = 1
if j == 1:
    print("The Suduko is not valid !")
else:
    print("The Suduko is valid in colom wise !")

The Suduko is valid in colom wise !


In [7]:
if i == 0 and j == 0 :
    print("The suduko is valid .. Overall ")
else:
    print("The suduko is not valid.. Overall")

The suduko is valid .. Overall 


**General Questions**

In [8]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [9]:
#Get the shape of the matrix.
matrix_space = data.shape
print("The shape of the matrix is :",matrix_space)

The shape of the matrix is : (5, 3)


In [10]:
#Find the average age of students.
age  = data[:,0]
sum =0
aver =0
for item in age:
    sum += item
aver = sum//age.size

print("The average age of the student is :",aver)

The average age of the student is : 18


In [11]:
#Extract Math marks of all students.
marks_math = data[:,1]
print("The all math marks of all students are :",marks_math)

The all math marks of all students are : [85 92 76 65 90]


In [12]:
#Find the highest Science mark.
marks_science = data[:,2]
height_marks = marks_science.max()
print("The height marks of the science subject is :",height_marks)

The height marks of the science subject is : 95


In [13]:
#Get details of the student who scored more than 90 in Math.
for itam in marks_math:
    if itam > 90:
        print(itam)

92


In [14]:
#Increase Math marks of all students by 5.
match_marks = np.array(marks_math)
incrise = match_marks + 5
print("The match marks befor incrising are :",match_marks)
print("The match marks after incrising by 5 are :",incrise)

The match marks befor incrising are : [85 92 76 65 90]
The match marks after incrising by 5 are : [90 97 81 70 95]


In [15]:
#Find how many students are younger than 19.
for yong in age:
    if yong <19:
        print("The yong boy age is :",yong)

The yong boy age is : 18
The yong boy age is : 17
The yong boy age is : 18


In [16]:
#Calculate the average marks in each subject (column-wise mean).
aver_scien = np.mean(marks_science)
aver_math = np.mean(marks_math)
print("The average marks of the science is :",aver_scien)
print("The average marks of the match is :",aver_math)

The average marks of the science is : 83.2
The average marks of the match is : 81.6


In [17]:
#Get data of students who scored at least 80 in both subjects.
marks_all = data[:,1:]
for i,j in marks_all:
    if i > 80 and j > 80:
        print("The marks of math ",i,"The science marks ",j)

The marks of math  92 The science marks  88
The marks of math  90 The science marks  85


In [21]:
#Replace all Science marks < 75 with 0.
data[data[:,2] < 75,2] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])