In [1]:
import numpy as np 
print(np.__version__)

2.5.1


In [2]:
X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

In [3]:
inputes = np.array(X)
inputes

array([[ 1. ,  2. ,  3. ,  2.5],
       [ 2. ,  5. , -1. ,  2. ],
       [-1.5,  2.7,  3.3, -0.8]])

In [4]:
inputes.shape

(3, 4)

In [5]:
Y = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]


In [6]:
weights = np.array(Y)
weights

array([[ 0.2 ,  0.8 , -0.5 ,  1.  ],
       [ 0.5 , -0.91,  0.26, -0.5 ],
       [-0.26, -0.27,  0.17,  0.87]])

In [7]:
weights.shape

(3, 4)

In [8]:
biases = [2.0, 3.0, 0.5]

In [9]:
weights = np.transpose(weights)

In [10]:
weights.shape

(4, 3)

In [11]:
dot_pro = np.dot(inputes,weights) + biases
dot_pro

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])