In [6]:
import numpy as np

In [8]:
rando = np.arange(1,21)
rando

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [10]:
rando_2D = rando.reshape(4,5)
rando_2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [11]:
rando_min = rando.min()
rando_min

np.int64(1)

In [12]:
rando_max = rando.max()
rando_max

np.int64(20)

In [14]:
size = rando.size
print("The size of the array is :",size)

The size of the array is : 20


In [15]:
data_type = rando.dtype
print("The data type of the arrat is :",data_type)

The data type of the arrat is : int64


In [19]:
zero_vector = np.zeros(5)
zero_vector

array([0., 0., 0., 0., 0.])

In [20]:
print("The data type of zero matrix is :",zero_matrix.dtype)

The data type of zero matrix is : float64


In [22]:
one_vactor = np.ones(5)
one_vactor

array([1., 1., 1., 1., 1.])

In [23]:
zero_matrix = np.zeros((3,5))
zero_matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
one_matrix = np.ones((4,5))
one_matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])