In [1]:
import numpy as np 
print(np.__version__)

2.5.1


In [4]:
random = .10*np.random.rand(4,5)

In [5]:
random

array([[0.08169876, 0.00847606, 0.00512946, 0.07268349, 0.08592521],
       [0.07635549, 0.02945109, 0.08012885, 0.00529673, 0.01702408],
       [0.01456515, 0.03158636, 0.06035114, 0.05947227, 0.06604492],
       [0.03403489, 0.09712754, 0.06909683, 0.04074466, 0.04276814]])

In [10]:
biase = np.zeros((1,5))

In [11]:
biase

array([[0., 0., 0., 0., 0.]])

In [12]:
X = [[1,2,3,2.5],[2,4,2.6,-1.9],[2.6,1.5,-2.5,0.9]]

In [13]:
class Layer_Dense:
    def __init__(self,n_input,n_nuren):
        self.weight = np.random.rand(n_input,n_nuren)
        self.bises = np.zeros((1,n_nuren))
    def forword(self,inputs):
        self.output = np.dot(inputs,self.weight) + self.bises

In [17]:
layer1 = Layer_Dense(4,6)
layer1.forword(X)
print(layer1.output)

[[ 4.91093023  7.62740033  3.38406919  4.03151129  3.80877754  4.75529528]
 [ 4.59065143  5.85257762  3.80283335 -0.25551903  3.1612182   3.92694526]
 [ 0.39605319  1.61309595  0.94010623  0.49974551  1.18309427  3.38655584]]


In [18]:
layer2 = Layer_Dense(6,5)
layer2.forword(layer1.output)
print(layer2.output)

[[18.61123437 14.6366423   9.81349373 10.42142592 14.398886  ]
 [15.68897882 12.27003457  7.77684644  9.25895012 11.88358809]
 [ 4.70316479  2.97762556  3.96154808  3.16111198  4.22734295]]


In [20]:
layer3 = Layer_Dense(5,2)
layer3.forword(layer2.output)
print(layer3.output) # this is the final output of the last layer.

[[44.60522776 43.97240388]
 [37.27699531 36.87561392]
 [12.99711246 13.32878299]]
